import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const NAVIGATION = [
  {
    segment: 'about',
    title: 'About',
    icon: 'info',
  },
  {
    segment: 'chat',
    title: 'Chat',
    icon: 'chat',
  },
  {
    segment: 'signIn',
    title: 'Sign In',
    icon: 'login',
  }
]

const BRANDING = {
  appName: "MyCoolApp",
  logo: "/logo.svg",
  primaryColor: "#0070f3",
  secondaryColor: "#ff4081",
  welcomeText: "Welcome to MyCoolApp!",
};


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <html lang="en">
        <body className="flex flex-col min-h-screen">
          <Navbar />
            <main className="flex-grow">{children}</main>
          <Footer />
        </body>
    </html>
  );
}

