import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NextAppProvider } from '@toolpad/core/nextjs';
import LinearProgress from '@mui/material/LinearProgress';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import React from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVIGATION = [
  {
    segment: 'about',
    title: 'About',
    icon: 'info',
  },
  {
    segment: 'chat',
    title: 'Chat',
    icon: 'chat',
  },
  {
    segment: 'signIn',
    title: 'Sign In',
    icon: 'login',
  }
]

const BRANDING = {
  appName: "MyCoolApp",
  logo: "/logo.svg",
  primaryColor: "#0070f3",
  secondaryColor: "#ff4081",
  welcomeText: "Welcome to MyCoolApp!",
};


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
  return (
    <AppRouterCacheProvider options={{ enableCssLayer: true}}>
      <React.Suspense fallback={<LinearProgress />}>
        <NextAppProvider navigation={NAVIGATION} branding={BRANDING}>
          <html lang="en">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              {children}
            </body>
          </html>
        </NextAppProvider>
      </React.Suspense>
    </AppRouterCacheProvider>
  );
}
