export const CATEGORY_SUBJECT_LIST = {
  psle: {
    science: 'Science',
    mathematics: 'Mathematics',
  },
  o_level: {
    combined_physics: 'Combined_Physics',
    combined_chemistry: 'Combined_Chemistry',
    combined_biology: 'Combined_Biology',
    pure_physics: 'Pure_Physics',
    pure_chemistry: 'Pure_Chemistry',
    pure_biology: 'Pure_Biology',
    add_math: 'Additional_Mathematics',
    elem_math: 'Elementary_Mathematics',
  },
  a_level: {
    h2_mathematics: 'H2_Mathematics',
    h1_mathematics: 'H1_Mathematics',
    h2_biology: 'H2_Biology',
    h1_biology: 'H1_Biology',
    h2_physics: 'H2_Physics',
    h1_physics: 'H1_Physics',
    h2_chemistry: 'H2_Chemistry',
    h1_chemistry: 'H1_Chemistry',
  },
  ib: {
    hl_mathematics: 'HL_Mathematics',
    sl_mathematics: 'SL_Mathematics',
    hl_biology: 'HL_Biology',
    sl_biology: 'SL_Biology',
    hl_physics: 'HL_Physics',
    sl_physics: 'SL_Physics',
    hl_chemistry: 'HL_Chemistry',
    sl_chemistry: 'SL_Chemistry',
  },
};